"""empty message

Revision ID: 1699ccd9a48e
Revises: 2c2aba979600
Create Date: 2024-07-13 01:16:26.237168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1699ccd9a48e'
down_revision = '2c2aba979600'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff', sa.Column('s_password', sa.String(length=128), nullable=False))
    op.drop_column('staff', 's_isAdmin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff', sa.Column('s_isAdmin', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('staff', 's_password')
    # ### end Alembic commands ###
