"""empty message

Revision ID: 2c2aba979600
Revises: 6c63d6fd5e5a
Create Date: 2024-07-13 01:12:26.075745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c2aba979600'
down_revision = '6c63d6fd5e5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff', sa.Column('s_password', sa.String(length=128), nullable=False))
    op.alter_column('staff', 's_isAdmin',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('staff', 's_isAdmin',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('staff', 's_password')
    # ### end Alembic commands ###
