"""empty message

Revision ID: 302da87f6b20
Revises: 1699ccd9a48e
Create Date: 2024-07-13 01:19:34.069019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '302da87f6b20'
down_revision = '1699ccd9a48e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff', sa.Column('s_isAdmin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('staff', 's_isAdmin')
    # ### end Alembic commands ###
