"""empty message

Revision ID: 4574f31598c3
Revises: a7a445607b95
Create Date: 2024-07-14 23:03:54.738369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4574f31598c3'
down_revision = 'a7a445607b95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('inventory_item', 'Item_SKU',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text('nextval(\'"inventory_item_Item_SKU_seq"\'::regclass)'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('inventory_item', 'Item_SKU',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text('nextval(\'"inventory_item_Item_SKU_seq"\'::regclass)'))
    # ### end Alembic commands ###
