"""empty message

Revision ID: 6c63d6fd5e5a
Revises: 73074a1a1087
Create Date: 2024-07-12 19:51:07.218043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c63d6fd5e5a'
down_revision = '73074a1a1087'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('c_ID', sa.Integer(), nullable=False),
    sa.Column('c_name', sa.String(length=64), nullable=True),
    sa.Column('c_email', sa.String(length=120), nullable=True),
    sa.Column('c_contact', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('c_ID')
    )
    op.create_index(op.f('ix_customer_c_contact'), 'customer', ['c_contact'], unique=True)
    op.create_index(op.f('ix_customer_c_email'), 'customer', ['c_email'], unique=True)
    op.create_index(op.f('ix_customer_c_name'), 'customer', ['c_name'], unique=True)
    op.create_table('inventory_item',
    sa.Column('Item_SKU', sa.Integer(), nullable=False),
    sa.Column('Item_Name', sa.String(length=64), nullable=True),
    sa.Column('Item_Description', sa.Text(), nullable=True),
    sa.Column('Item_Price', sa.Float(), nullable=True),
    sa.Column('Item_Qty', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('Item_SKU')
    )
    op.create_index(op.f('ix_inventory_item_Item_Name'), 'inventory_item', ['Item_Name'], unique=True)
    op.create_table('staff',
    sa.Column('s_ID', sa.Integer(), nullable=False),
    sa.Column('s_name', sa.String(length=64), nullable=True),
    sa.Column('s_email', sa.String(length=120), nullable=True),
    sa.Column('s_isAdmin', sa.Integer(), nullable=True),
    sa.Column('s_contact', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('s_ID')
    )
    op.create_index(op.f('ix_staff_s_contact'), 'staff', ['s_contact'], unique=True)
    op.create_index(op.f('ix_staff_s_email'), 'staff', ['s_email'], unique=True)
    op.create_index(op.f('ix_staff_s_name'), 'staff', ['s_name'], unique=True)
    op.create_table('transaction',
    sa.Column('t_ID', sa.Integer(), nullable=False),
    sa.Column('c_ID', sa.Integer(), nullable=True),
    sa.Column('s_ID', sa.Integer(), nullable=True),
    sa.Column('t_date', sa.DateTime(), nullable=False),
    sa.Column('t_amount', sa.Integer(), nullable=True),
    sa.Column('t_category', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['c_ID'], ['customer.c_ID'], ),
    sa.ForeignKeyConstraint(['s_ID'], ['staff.s_ID'], ),
    sa.PrimaryKeyConstraint('t_ID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction')
    op.drop_index(op.f('ix_staff_s_name'), table_name='staff')
    op.drop_index(op.f('ix_staff_s_email'), table_name='staff')
    op.drop_index(op.f('ix_staff_s_contact'), table_name='staff')
    op.drop_table('staff')
    op.drop_index(op.f('ix_inventory_item_Item_Name'), table_name='inventory_item')
    op.drop_table('inventory_item')
    op.drop_index(op.f('ix_customer_c_name'), table_name='customer')
    op.drop_index(op.f('ix_customer_c_email'), table_name='customer')
    op.drop_index(op.f('ix_customer_c_contact'), table_name='customer')
    op.drop_table('customer')
    # ### end Alembic commands ###
