"""empty message

Revision ID: a7a445607b95
Revises: 302da87f6b20
Create Date: 2024-07-13 02:02:40.702409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7a445607b95'
down_revision = '302da87f6b20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff', sa.Column('s_isAdmin', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('staff', 's_isAdmin')
    # ### end Alembic commands ###
